name: Integration Test Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/HurricanKai/publish-docker-github-action/publish-docker-github-action
        username: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
        password: ${{ secrets. GITHUB_DOCKER_USERNAME }}
        registry: docker.pkg.github.com
